---

# Format is:
# - enum name:
#   - xml tag 1:
#     - sub tag 1
#     - sub tag 2
#   - xml tag 2:
#     - sub tag 1

- RUNWAY:
  - aeroway:
    - runway
    - taxiway

- APRON:
  - aeroway:
    - apron

- MARKING:
  - aeroway:
    - marking

- BRIDLEWAY:
  - highway:
    - bridleway

- BUILDING:
  - amenity:
      - university

- CYCLEWAY:
  - highway:
    - cycleway

- FOOTWAY:
  - highway:
    - footway

- LIVING_STREET:
  - highway:
    - living_street

- MOTORWAY:
  - highway:
    - motorway
    - motorway_link

- PEDESTRIAN:
  - highway:
    - pedestrian

- PRIMARY_ROAD:
  - highway:
    - primary
    - trunk
    - primary_link
    - trunk_link

- RACEWAY:
  - highway:
    - raceway

- RESIDENTIAL_ROAD:
  - highway:
    - residential

- SECONDARY_ROAD:
  - highway:
    - secondary
    - secondary_link

- SERVICE_ROAD:
  - highway:
    - service

- TERTIARY_ROAD:
  - highway:
    - tertiary
    - tertiary_link

- TRACK:
  - highway:
    - track
    - path
    - steps

- UNCLASSIFIED_ROAD:
  - highway:
    - unclassified

- ALLOTMENTS:
  - landuse:
    - allotments

- BASIN:
  - landuse:
    - basin

- BROWNFIELD:
  - landuse:
    - brownfield

- CEMETERY:
  - landuse:
    - cemetery

- CONSTRUCTION:
  - landuse:
    - construction

- FARMLAND:
  - landuse:
    - farmland

- GRASS:
  - landuse:
    - grass

- INDUSTRIAL:
  - landuse:
    - industrial

- MEADOW:
  - landuse:
    - meadow

- PITCH:
  - leisure

- PARK:
  - leisure:
    - park
    - garden

- PLAYGROUND:
  - leisure:
    - playground

- SWIMMINGPOOL:
  - leisure:
    - swimming_pool

- BRIDGE:
  - man_made:
    - bridge

- GROYNE:
  - man_made:
    - groyne

- PIER:
  - man_made:
    - pier

- SAND:
  - natural:
    - beach

- COASTLINE:
  - place:
    - island
    - peninsula
    - islet
    - archipelago

- HEATH:
  - natural:
    - heath

- SCREE:
  - natural:
    - scree

- TREES:
  - natural:
    - tree
  - landuse:
    - forest

- WATER:
  - natural:
    - water
  - shrub:
    - water

- WETLAND:
  - natural:
    - wetland

- WOOD:
  - natural:
    - wood

- RAILWAY:
  - railway:
    - rail
    - construction

- RESIDENTIAL:
  - residential

- CANAL:
  - water:
    - canal
    - pond
    - reservoir