---

# The format is:
# way type name:
#   fillColor: "Web color"
#   strokeColor: "Web color"
#   lineDash: Number
#   lineWidth: Number
#   texture: Path
#
# For more about web color formats, see:
# https://docs.oracle.com/javase/8/javafx/api/javafx/scene/paint/Color.html

# Constants, won't get parsed but are used for anchor references

- constants:
  - zoomLevels:
    - level1: &level1 0.001
    - level2: &level2 0.00003
    - level3: &level3 0.00002
    - level4: &level4 0.00001
    - level5: &level5 0.000002
    - level6: &level6 0.000004
    - level7: &level7 0.000006
    - level8: &level8 0.00000065

# Coastline, always draw first

- COASTLINE:
    fillColor: "EEF0D5"
    alwaysDraw: true

# Island stuff

- ISLAND:
    fillColor: "F4F0EA"
    alwaysDraw: true

- SCREE:
    fillColor: "F1E5DC"
    alwaysDraw: true

# Nature

- TREES:
    fillColor: "006400"
    zoomLevel: *level1

- GRASS:
    fillColor: "C4EDB2"

- SAND:
    fillColor: "FFF1BA"

- FARMLAND:
    fillColor: "EFF1D5"
    zoomLevel: *level1

- WOOD:
    fillColor: "A1D29F"
    zoomLevel: *level1

- HEATH:
    fillColor: "D6D99F"

- MEADOW:
    fillColor: "C4EDB2"

- PARK:
    fillColor: "90EE90"

- WETLAND:
    fillColor: "ADD8E6"

- BROWNFIELD:
    fillColor: "D2B48C"

- SHRUB:
    fillColor: "90EE90"

# Buildings

- CONSTRUCTION:
    fillColor: "8FBC8F"
    zoomLevel: *level2

- INDUSTRIAL:
    fillColor: "D8BFD8"
    zoomLevel: *level2

- CEMETERY:
    fillColor: "6B8E23"
    zoomLevel: *level2

- RESIDENTIAL:
    fillColor: "E6E6FA"
    zoomLevel: *level2

- ALLOTMENTS:
    fillColor: "98FB98"
    zoomLevel: *level2

- PLAYGROUND:
    fillColor: "66CDAA"
    zoomLevel: *level2

- BUILDING:
    fillColor: "A9A9A9"
    zoomLevel: *level2

- BARRIER:
    strokeColor: "BC8F8F"
    zoomLevel: *level2

- PITCH:
    fillColor: "66CDAA"
    zoomLevel: *level2

- GROYNE:
    fillColor: "A9A9A9"
    zoomLevel: *level2

- PIER:
    fillColor: "FFFF00"
    strokeColor: "FFFF00"
    zoomLevel: *level2

- BRIDGE:
    fillColor: "BDB76B"
    strokeColor: "BDB76B"
    zoomLevel: *level2

- APRON:
    fillColor: "DADAE0"
    zoomLevel: *level2

# Road exits

- TERTIARYROADEXIT:
    fillColor:
    strokeColor: "FFFFFF"
    lineWidth: 0.00008
    zoomLevel: *level4

- SECONDARYROADEXIT:
    fillColor:
    strokeColor: "F7FBBB"
    lineWidth: 0.00012
    zoomLevel: *level3

- PRIMARYROADEXIT:
    fillColor:
    strokeColor: "FFAD95"
    lineWidth: 0.00012
    zoomLevel: *level2

- MOTORWAYEXIT:
    fillColor:
    strokeColor: "FEB9C3"
    lineWidth: 0.00014
    zoomLevel: *level1

# Roads

- RESIDENTIALROAD:
    fillColor:
    strokeColor: "FFFFFF"
    lineWidth: 0.00006
    zoomLevel: *level4

- TERTIARYROAD:
    fillColor:
    strokeColor: "FFFFFF"
    lineWidth: 0.00008
    zoomLevel: *level4

- SERVICEROAD:
    fillColor:
    strokeColor: "FFFFFF"
    lineWidth: 0.00004
    zoomLevel: *level5

- UNCLASSIFIEDROAD:
    fillColor:
    strokeColor: "FFFFFF"
    lineWidth: 0.00006
    zoomLevel: *level6


- ROUNDABOUT:
    fillColor:
    strokeColor: "FFFFFF"
    lineWidth: 0.00008
    zoomLevel: *level3

- LIVING_STREET:
    fillColor:
    strokeColor: "EDEEED"
    lineWidth: 0.00006
    zoomLevel: *level4

- SECONDARYROAD:
    fillColor:
    strokeColor: "F7FBBB"
    lineWidth: 0.00012
    zoomLevel: *level3

- PRIMARYROAD:
    fillColor:
    strokeColor: "FFAD95"
    lineWidth: 0.00012
    zoomLevel: *level2

- RUNWAY:
    fillColor:
    strokeColor: "BABACC"
    lineWidth: 0.0005
    zoomLevel: *level3

- RAILWAY:
    fillColor:
    strokeColor: "D3D3D3"
    lineDash: 2
    zoomLevel: *level3

- PEDESTRIAN:
    fillColor:
    strokeColor: "DDDDE9"
    lineWidth: 0.00005
    zoomLevel: *level6

- RACEWAY:
    fillColor:
    strokeColor: "FFBDC7"
    lineWidth: 0.00004
    zoomLevel: *level8

- MOTORWAY:
    fillColor:
    strokeColor: "FEB9C3"
    lineWidth: 0.00014
    zoomLevel: 0.001

# Abstract routes

- MARKING:
    fillColor:
    strokeColor: "000000"
    zoomLevel: *level7

- TRACK:
    fillColor:
    strokeColor: "B68235"
    lineDash: 2
    zoomLevel: *level7

- FERRY:
    fillColor:
    strokeColor: "0000FF"
    lineDash: 2
    zoomLevel: *level7

- TOUR:
    fillColor:
    strokeColor: "000000"
    lineDash: 2
    zoomLevel: *level7

- BUS_GUIDEWAY:
    fillColor:
    strokeColor: "6066FF"
    lineDash: 2
    zoomLevel: *level7

- FOOTWAY:
    fillColor:
    strokeColor: "FE9E93"
    zoomLevel: *level7

- BRIDLEWAY:
    fillColor:
    strokeColor: "A8D7B6"
    lineDash: 2
    zoomLevel: *level7

- CYCLEWAY:
    fillColor:
    strokeColor: "7B7EF8"
    zoomLevel: *level7

# Water

- WATER:
    fillColor: "87CEFA"

- SWIMMINGPOOL:
    fillColor: "87CEFA"

- CANAL:
    fillColor: "87CEFA"

- BASIN:
    fillColor: "87CEFA"

# Misc.
