---

# Format is:
# - enum name:
#   - xml tag 1:
#     - sub tag 1
#     - sub tag 2
#   - xml tag 2:
#     - sub tag 1

- RUNWAY:
  - aeroway:
    - runway
    - taxiway

- APRON:
  - aeroway:
    - apron

- MARKING:
  - aeroway:
    - marking

- BARRIER:
  - barrier

- BRIDLEWAY:
  - highway:
    - bridleway

- BUILDING:
  - building

- BUS_GUIDEWAY:
  - highway:
    - bus_guideway

- CYCLEWAY:
  - highway:
    - cycleway

- FOOTWAY:
  - highway:
    - footway

- LIVING_STREET:
  - highway:
    - living_street

- MOTORWAY:
  - highway:
    - motorway

- MOTORWAYEXIT:
  - highway:
    - motorway_link

- PEDESTRIAN:
  - highway:
    - pedestrian

- PRIMARYROAD:
  - highway:
    - primary
    - trunk

- PRIMARYROADEXIT:
  - highway:
    - primary_link
    - trunk_link

- RACEWAY:
  - highway:
    - raceway

- RESIDENTIALROAD:
  - highway:
    - residential

- SECONDARYROAD:
  - highway:
    - secondary

- SECONDARYROADEXIT:
  - highway:
    - secondary_link

- SERVICEROAD:
  - highway:
    - service

- TERTIARYROAD:
  - highway:
    - tertiary

- TERTIARYROADEXIT:
  - high:
    - tertiary_link

- TRACK:
  - highway:
    - track

- UNCLASSIFIEDROAD:
  - highway:
    - unclassified

- ROUNDABOUT:
  - junction:
    - roundabout

- ALLOTMENTS:
  - landuse:
    - allotments

- BASIN:
  - landuse:
    - basin

- BROWNFIELD:
  - landuse:
    - brownfield

- CEMETERY:
  - landuse:
    - cemetery

- CONSTRUCTION:
  - landuse:
    - construction

- FARMLAND:
  - landuse:
    - farmland

- GRASS:
  - landuse:
    - grass

- INDUSTRIAL:
  - landuse:
    - industrial

- MEADOW:
  - landuse:
    - meadow

- PITCH:
  - leisure

- PARK:
  - leisure:
    - park
    - garden

- PLAYGROUND:
  - leisure:
    - playground

- SWIMMINGPOOL:
  - leisure:
    - swimming_pool

- BRIDGE:
  - man_made:
    - bridge

- GROYNE:
  - man_made:
    - groyne

- PIER:
  - man_made:
    - pier

- SAND:
  - natural:
    - beach

- COASTLINE:
  - natural:
    - coastline

- HEATH:
  - natural:
    - heath

- SCREE:
  - natural:
    - scree

- TREES:
  - natural:
    - tree
  - landuse:
    - forest

- WATER:
  - natural:
    - water
  - shrub:
    - water

- WETLAND:
  - natural:
    - wetland

- WOOD:
  - natural:
    - wood

- ISLAND:
  - place:
    - island

- RAILWAY:
  - railway:
    - rail
    - construction

- RESIDENTIAL:
  - residential

- FERRY:
  - route:
    - ferry tour

- CANAL:
  - water:
    - canal
    - pond
    - reservoir