---

# The format is:
# way type name:
#   fillColor: "Web color"
#   strokeColor: "Web color"
#   lineDash: Number
#   lineWidth: Number
#   texture: Path
#
# For more about web color formats, see:
# https://docs.oracle.com/javase/8/javafx/api/javafx/scene/paint/Color.html

# Constants, won't get parsed but are used for anchor references

- COASTLINE:
    fillColor:
    texture: "textures/ground.jpg"

- TREES:
    fillColor:
    texture: "textures/woods.jpg"

- GRASS:
    fillColor:
    texture: "textures/woods.jpg"

- MEADOW:
    fillcolor:
    texture: "textures/stylised.jpg"

- HEATH:
    fillcolor:
    texture: "textures/stylised.jpg"

- FARMLAND:
    fillColor:
    texture: "textures/farm.jpg"

- SAND:
    fillColor:
    texture: "textures/sand.jpg"

- MOTORWAY:
      fillColor:
      strokeColor: "E43D1A"
      lineWidth: 0.0005
      zoomLevel: