---

# The format is:
# way type name:
#   fillColor: "Web color"
#   strokeColor: "Web color"
#   lineDash: Number
#   lineWidth: Number
#   texture: Path
#
# For more about web color formats, see:
# https://docs.oracle.com/javase/8/javafx/api/javafx/scene/paint/Color.html

# Constants, won't get parsed but are used for anchor references

- COASTLINE:
    fillColor:
    texture: "textures/ground.jpg"

- TREES:
    fillColor:
    texture: "textures/forest-texture.jpg"

- GRASS:
    fillColor:
    texture: "textures/grass.jpg"

- FARMLAND:
    fillColor:
    texture: "textures/farmland.jpg"

- SAND:
    fillColor:
    texture: "textures/coastline-seamless.jpg"